name: 🐛 バグ修正
description: バグや不具合の修正
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: problem
    attributes:
      label: 問題
      description: 発生している問題を記載

  - type: textarea
    id: cause
    attributes:
      label: 原因分析
      description: 問題の原因（判明している場合）

  - type: textarea
    id: reproduction
    attributes:
      label: 再現手順
      description: 問題を再現する手順

  - type: textarea
    id: solution
    attributes:
      label: 解決方針
      description: 修正の方針・方法

  - type: dropdown
    id: priority
    attributes:
      label: 優先度
      options:
        - Critical
        - High
        - Medium
        - Low

  - type: textarea
    id: acceptance
    attributes:
      label: 受け入れ条件
      description: |
        修正完了の判定基準
        - [ ]
        - [ ]
        - [ ]

  - type: textarea
    id: screenshots
    attributes:
      label: スクリーンショット・ファイル
      description: |
        関連する画像、ログファイル、エラーメッセージなど
        画像をドラッグ&ドロップまたは貼り付けてください

        ```
        ログやエラーメッセージをここに貼り付け
        ```

  - type: textarea
    id: notes
    attributes:
      label: 補足
      description: その他の情報