name: 🐛 バグレポート (Bug Report)
description: バグや不具合を報告する (Report a bug or issue)
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        バグレポートありがとうございます。問題をより迅速に解決するため、以下の情報をできるだけ詳しく記入してください。

  - type: input
    id: version
    attributes:
      label: バージョン (Version)
      description: 使用しているアプリのバージョンを記載してください
      placeholder: "例: v1.0.0, main branch, commit hash"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: 動作環境 (Operating System)
      description: 問題が発生したOSを選択してください
      options:
        - Windows 10/11
        - macOS (Intel)
        - macOS (Apple Silicon)
        - Ubuntu/Debian
        - その他 Linux
        - その他
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: 問題の概要 (Bug Description)
      description: 発生している問題を簡潔に説明してください
      placeholder: "例: 字幕抽出処理中にアプリケーションがクラッシュする"
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: 再現手順 (Steps to Reproduce)
      description: 問題を再現するための具体的な手順を記載してください
      placeholder: |
        1. アプリを起動する
        2. 動画ファイル（XXX形式、XX分）を読み込む
        3. 字幕抽出を開始する
        4. エラーが発生する
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: 期待される動作 (Expected Behavior)
      description: 本来どのような動作を期待していたかを記載してください
      placeholder: "例: 字幕抽出が正常に完了し、SRTファイルが生成される"
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: 実際の動作 (Actual Behavior)
      description: 実際に何が起こったかを記載してください
      placeholder: "例: 処理中にアプリケーションが予期せず終了し、エラーメッセージが表示された"
    validations:
      required: true

  - type: textarea
    id: error-logs
    attributes:
      label: エラーログ・スクリーンショット (Error Logs / Screenshots)
      description: |
        エラーメッセージ、ログファイル、スクリーンショットなどを貼り付けてください。
        ログファイルは `vlog-subs-tool-debug.log` にあります。
      placeholder: |
        ```
        エラーメッセージをここに貼り付けてください
        ```

        または画像をドラッグ＆ドロップしてください
    validations:
      required: false

  - type: textarea
    id: video-info
    attributes:
      label: 動画ファイル情報 (Video File Information)
      description: 問題が発生した動画ファイルの情報を記載してください
      placeholder: |
        - ファイル形式: MP4
        - 解像度: 1920x1080
        - 長さ: 30分
        - ファイルサイズ: 500MB
        - 字幕の位置: 下部
        - 字幕の言語: 日本語
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: 優先度 (Priority)
      description: この問題の優先度を選択してください
      options:
        - Critical (重大) - アプリが使用不可
        - High (高) - 主要機能に影響
        - Medium (中) - 一部機能に影響
        - Low (低) - 軽微な問題
    validations:
      required: true

  - type: checkboxes
    id: additional-info
    attributes:
      label: 追加情報 (Additional Information)
      description: 該当するものにチェックを入れてください
      options:
        - label: 他のバージョンでも同じ問題が発生する
        - label: 特定の動画ファイルでのみ発生する
        - label: 回避方法を知っている
        - label: ウイルス対策ソフトが有効
        - label: 管理者権限で実行している

  - type: textarea
    id: additional-context
    attributes:
      label: 補足情報 (Additional Context)
      description: その他、問題解決に役立つ情報があれば記載してください
      placeholder: "例: 特定の条件下でのみ発生する、以前は正常に動作していた、など"
    validations:
      required: false