name: ✨ 機能実装
description: 新機能や改善の実装
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: overview
    attributes:
      label: 機能概要
      description: 実装する機能の概要
    validations:
      required: true

  - type: textarea
    id: background
    attributes:
      label: 背景・目的
      description: なぜこの機能が必要か
    validations:
      required: true

  - type: textarea
    id: specification
    attributes:
      label: 仕様・要件
      description: 機能の詳細仕様
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: 優先度
      options:
        - Critical
        - High
        - Medium
        - Low
    validations:
      required: true

  - type: textarea
    id: technical_approach
    attributes:
      label: 技術的アプローチ
      description: 実装方針・技術的考慮事項
    validations:
      required: false

  - type: textarea
    id: acceptance
    attributes:
      label: 受け入れ条件
      description: |
        実装完了の判定基準
        - [ ]
        - [ ]
        - [ ]
    validations:
      required: true