name: 🔍 技術調査・検討
description: 技術的な調査や検討事項
title: "[Research]: "
labels: ["research", "investigation"]
body:
  - type: textarea
    id: topic
    attributes:
      label: 調査・検討事項
      description: 調査・検討する内容

  - type: textarea
    id: background
    attributes:
      label: 背景
      description: なぜ調査・検討が必要か

  - type: textarea
    id: questions
    attributes:
      label: 調査項目・課題
      description: |
        調査すべき項目や解決すべき課題
        -
        -
        -

  - type: textarea
    id: approach
    attributes:
      label: 調査方法・アプローチ
      description: 調査の進め方

  - type: dropdown
    id: priority
    attributes:
      label: 優先度
      options:
        - Critical
        - High
        - Medium
        - Low

  - type: textarea
    id: deliverables
    attributes:
      label: 成果物
      description: |
        調査結果として期待する成果物
        - [ ]
        - [ ]
        - [ ]

  - type: textarea
    id: references
    attributes:
      label: 参考資料・画像
      description: |
        関連する資料、グラフ、図表、スクリーンショットなど
        画像をドラッグ&ドロップまたは貼り付けてください

  - type: textarea
    id: notes
    attributes:
      label: 補足
      description: その他の情報